### ISSUE TITLE
Geen css in de html

### ISSUE THREAD

**Issue by CelinexPutte** [maikangn/Lifely-Getting-Started-With-AI#5]
Style de afbeelding met `width` in je css document en niet in de html.

https://github.com/maikangn/the-startup-responsive-interactieve-website/blob/40e01ebf5478c4072e244152d97ad7ff5a14c65f/index.html#L58

**Comment by KrijnHoetmer** [comment]
Dit zou ik juist wel doen. Zie ook https://web.dev/top-cwv-2023/ en specifiek https://web.dev/top-cwv-2023/#set-explicit-sizes-on-any-content-loaded-from-the-page.
